/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-17 12:45:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.community.parcelout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pinkpaw.member.model.vo.Member;
import com.pinkpaw.member.model.vo.Member;

public final class parceloutWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1566045381359L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1566045381375L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pinkpaw.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
//로그인성공후 session객체에 저장된 memberLoggedIn가져오기
Member memberLoggedIn
	= (Member)session.getAttribute("memberLoggedIn");
System.out.println("memberLoggedIn@index.jsp="+memberLoggedIn);
/* memberLoggedIn = new Member();
memberLoggedIn.setMemberId("admin");
System.out.println("memberLoggedIn@index.jsp="+memberLoggedIn); */

//쿠키관련 처리
Cookie[] cookies = request.getCookies();
boolean saveId = false;
String memberId = "";

if(cookies != null){
	System.out.println("-------------------------");
	for(Cookie c: cookies){
		String key = c.getName();
		String value = c.getValue();
		System.out.println(key+" : "+value);
		
		//전송된 saveId쿠키가 있는 경우
		if("saveId".equals(key)){
			saveId = true;
			memberId = value;
		}
	}
	System.out.println("-------------------------");
}




	

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PinkPaw</title>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--<link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">-->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,target-densitydpi=medium-dpi\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/reset.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/Font.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/Swiper.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-migrate-3.0.0.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/swiper.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.mousewheel.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Noto+Sans|Noto+Sans+KR:100,300,400,500,700,900\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function register(){\r\n");
      out.write("\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/member/termsOfService\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\t\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validate(){\r\n");
      out.write("\tif($(\"#memberId\").val().trim().length == 0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#password\").val().trim().length == 0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#password\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--header-->\r\n");
      out.write("\t<div class=\"headerWrap\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h1  style=\"width: 800px; margin-left: -20px;\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/main/logo_color.png\" alt=\"logo\" style=\"margin-top: -9px;\"></a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("​\r\n");
      out.write("\t\t\t$('.headerWrap').mouseover(function(e){\r\n");
      out.write("\t\t\t\t$(this).css('background','rgba(34,34,34,0.7)');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('.headerWrap').mouseout(function(e){\r\n");
      out.write("\t\t\t\t$(this).css('background','none');}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("​\r\n");
      out.write("\t\t\t$('header>div>ul:first-child>li').mouseover(function(e){\r\n");
      out.write("\t\t\t\t$('.headerWrap').css('height','140px');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t$('header>div>ul:first-child>li').mouseout(function(e){\r\n");
      out.write("\t\t\t\t$('.headerWrap').css('height','84px');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t​ <a href=\"#none\" onClick=\"$('.menuWrap').fadeIn(300);\"><img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/images/main/icon_meun.png\" alt=\"메뉴바\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t​ ​\r\n");
      out.write("\t<!--menu-->\r\n");
      out.write("\t<div class=\"menuWrap\">\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<a href=\"#none\" onClick=\"$('.menuWrap').fadeOut(300);\"\r\n");
      out.write("\t\t\t\tclass=\"menu_closeBtn\"><img src=\"images/main/modal_close.gif\"\r\n");
      out.write("\t\t\t\talt=\"닫기\"></a>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 if(memberLoggedIn == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" \r\n");
      out.write("\t\t\t\t\t  id=\"loginFrm\"\r\n");
      out.write("\t\t\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t\t\t  onsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   placeholder=\"아이디\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"1\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   value=\"");
      out.print(saveId?memberId:"");
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"3\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   placeholder=\"비밀번호\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"2\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   ");
      out.print(saveId?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"saveId\">아이디저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-primary\" \r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"회원가입\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"register();\" >회원가입</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t");
 } 
			//로그인에 성공한 경우
			else {
      out.write("\t\r\n");
      out.write("\t\t\t\t<table id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(memberLoggedIn.getMemberName() );
      out.write("님, 안녕하세요.\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"쪽지\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/board/dm/dmView\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"신고쪽지\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/board/dm/reportDMList'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"신고게시판\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/reportBoardList'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t   \t   \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"마이페이지\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberView?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"내가쓴글보기\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myBoard'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"내가쓴댓글보기\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myComment'\"/>\t   \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"로그아웃\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/notice/noticeBoardList\">공지사항</a>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt class=\"sub_menu\">유기동물</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/organic/graph/OrganicGraph\">유기동물 통계</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/animal/animalNotice\">유기동물 공고</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl class=\"ddSize\">\r\n");
      out.write("\t\t\t\t<dt class=\"sub_menu\">보호소</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/shelter/shelterList\">보호소 찾기</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/volunteer/volunteerList\">보호소 봉사요청</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt class=\"sub_menu\">커뮤니티</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/missingList\">실종동물</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/parcelout/parceloutList\">분양동물</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/review/reviewList\">후기</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/community/free/freeList\">자유게시판</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원리스트</a>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(()=>{\r\n");
      out.write("\t\t\t$(\".sub_menu\").on(\"click\", function(e){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).parent().siblings().children(\"dd\").css('display','none');\r\n");
      out.write("\t\t\t\t$(this).siblings().css('display','inline-block');\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>​\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--menu end-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--header end-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<style>\r\n");
      out.write("#fileField {\r\n");
      out.write("position: relative;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$('document').ready(function() {\r\n");
      out.write(" var area0 = [\"시/도 선택\",\"서울특별시\",\"인천광역시\",\"대전광역시\",\"광주광역시\",\"대구광역시\",\"울산광역시\",\"부산광역시\",\"경기도\",\"강원도\",\"충청북도\",\"충청남도\",\"전라북도\",\"전라남도\",\"경상북도\",\"경상남도\",\"제주도\",\"세종특별자치시\"];\r\n");
      out.write("  var area1 = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("   var area2 = [\"계양구\",\"남동구\",\"동구\",\"미추홀구\",\"부평구\",\"서구\",\"연수구\",\"중구\",\"강화군\",\"옹진군\"];\r\n");
      out.write("   var area3 = [\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"];\r\n");
      out.write("   var area4 = [\"광산구\",\"남구\",\"동구\",\"북구\",\"서구\"];\r\n");
      out.write("   var area5 = [\"남구\",\"달서구\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\",\"달성군\"];\r\n");
      out.write("   var area6 = [\"남구\",\"동구\",\"북구\",\"중구\",\"울주군\"];\r\n");
      out.write("   var area7 = [\"강서구\",\"금정구\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\",\"기장군\"];\r\n");
      out.write("   var area8 = [\"고양시\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시\",\"수원시\",\"시흥시\",\"안산시\",\"안성시\",\"안양시\",\"양주시\",\"여주시\",\"오산시\",\"용인시\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\",\"가평군\",\"양평군\",\"연천군\"];\r\n");
      out.write("   var area9 = [\"강릉시\",\"동해시\",\"삼척시\",\"속초시\",\"원주시\",\"춘천시\",\"태백시\",\"고성군\",\"양구군\",\"양양군\",\"영월군\",\"인제군\",\"정선군\",\"철원군\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("   var area10 = [\"제천시\",\"청주시\",\"충주시\",\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"증평군\",\"진천군\"];\r\n");
      out.write("   var area11 = [\"계룡시\",\"공주시\",\"논산시\",\"당진시\",\"보령시\",\"서산시\",\"아산시\",\"천안시\",\"금산군\",\"부여군\",\"서천군\",\"연기군\",\"예산군\",\"청양군\",\"태안군\",\"홍성군\"];\r\n");
      out.write("   var area12 = [\"군산시\",\"김제시\",\"남원시\",\"익산시\",\"전주시\",\"정읍시\",\"고창군\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"임실군\",\"장수군\",\"진안군\"];\r\n");
      out.write("   var area13 = [\"광양시\",\"나주시\",\"목포시\",\"순천시\",\"여수시\",\"강진군\",\"고흥군\",\"곡성군\",\"구례군\",\"담양군\",\"무안군\",\"보성군\",\"신안군\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"];\r\n");
      out.write("   var area14 = [\"경산시\",\"경주시\",\"구미시\",\"김천시\",\"문경시\",\"상주시\",\"안동시\",\"영주시\",\"영천시\",\"포항시\",\"고령군\",\"군위군\",\"봉화군\",\"성주군\",\"영덕군\",\"영양군\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\"];\r\n");
      out.write("   var area15 = [\"거제시\",\"김해시\",\"밀양시\",\"사천시\",\"양산시\",\"진주시\",\"창원시\",\"통영시\",\"거창군\",\"고성군\",\"남해군\",\"산청군\",\"의령군\",\"창녕군\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"];\r\n");
      out.write("   var area16 = [\"서귀포시\",\"제주시\"];\r\n");
      out.write("   var area16 = [\"\"];\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" // 시/도 선택 박스 초기화\r\n");
      out.write("\r\n");
      out.write(" $(\"select[name^=sido]\").each(function() {\r\n");
      out.write("  $selsido = $(this);\r\n");
      out.write("  $.each(eval(area0), function() {\r\n");
      out.write("   $selsido.append(\"<option value='\"+this+\"'>\"+this+\"</option>\");\r\n");
      out.write("  });\r\n");
      out.write("  $selsido.next().append(\"<option value=''>구/군 선택</option>\");\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write(" // 시/도 선택시 구/군 설정\r\n");
      out.write("\r\n");
      out.write(" $(\"select[name^=sido]\").change(function() {\r\n");
      out.write("  var area = \"area\"+$(\"option\",$(this)).index($(\"option:selected\",$(this))); // 선택지역의 구군 Array\r\n");
      out.write("  var $gugun = $(this).next(); // 선택영역 군구 객체\r\n");
      out.write("  $(\"option\",$gugun).remove(); // 구군 초기화\r\n");
      out.write("\r\n");
      out.write("  if(area == \"area0\")\r\n");
      out.write("   $gugun.append(\"<option value=''>시/군/구 선택</option>\");\r\n");
      out.write("  else {\r\n");
      out.write("   $.each(eval(area), function() {\r\n");
      out.write("    $gugun.append(\"<option value='\"+this+\"'>\"+this+\"</option>\");\r\n");
      out.write("   });\r\n");
      out.write("  }\r\n");
      out.write(" });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>분양 글쓰기</h2>\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/parceloutboard/parceloutWriteEnd\"\r\n");
      out.write("\t      method=\"post\"\r\n");
      out.write("\t      enctype=\"multipart/form-data\">\r\n");
      out.write("\t      \r\n");
      out.write("\t\t<table id=\"tbl-board-view\" style=\"margin-top: 100px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"parceloutTitle\" required/></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t   name=\"parceloutWriter\"\r\n");
      out.write("\t\t\t\t\t\t   value=\"");
      out.print(memberLoggedIn.getMemberId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t   required readonly/></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>분양지역</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"sido\" id=\"sido\"></select>\r\n");
      out.write("\t\t\t\t\t<select name=\"gugun\" id=\"gugun\"></select>\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>책임비</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"parceloutMoney\" value=\"10000\" >1만원\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"parceloutMoney\" value=\"20000\" >2만원\r\n");
      out.write("    \t\t\t<input type=\"radio\" name=\"parceloutMoney\" value=\"30000\" >3만원\r\n");
      out.write("    \t\t\t<input type=\"radio\" name=\"parceloutMoney\" value=\"40000\" >4만원\r\n");
      out.write("    \t\t\t<input type=\"radio\" name=\"parceloutMoney\" value=\"50000\" >5만원\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>분류</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"radio\" id=\"animal-dog\" name=\"parceloutKind\" value=\"개\" />개\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"animal-cat\" name=\"parceloutKind\" value=\"고양이\" />고양이\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" id=\"animal\" name=\"parceloutKind\" value=\"animal\" />기타&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<div id='show-me' style='display: none'>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"animal-and\" name=\"others\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"기타 분류 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>암수구분</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"parceloutGender\" value=\"m\" >수컷\r\n");
      out.write("\t\t\t    <input type=\"radio\" name=\"parceloutGender\" value=\"f\">암컷\r\n");
      out.write("    \t\t\t<input type=\"radio\" name=\"parceloutGender\" value=\"s\" >한쌍\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<textarea name=\"parceloutContent\" \r\n");
      out.write("\t\t\t\t\t\t\t  cols=\"40\" rows=\"20\" required></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>사진첨부</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t첫번째로 첨부된 사진이 메인사진으로 등록됩니다.<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" name=\"upFile\" onchange=\"previewImage(this,'view_area')\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"추가\" onclick=\"attachFile.add()\"><br/>\r\n");
      out.write("\t\t\t\t\t<div id='view_area' style='position:relative; width: 100px; height: 100px; display: none; '></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"attachFileDiv\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\t    \r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" \r\n");
      out.write("\t\t\t\t\t\t   value=\"등록\" \r\n");
      out.write("\t\t\t\t\t\t   onclick=\"return parceloutValidate();\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t   value=\"취소\" \r\n");
      out.write("\t\t\t\t\t\t   onclick=\"goList();\"/>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\"input[id='animal']\").click(function () {\r\n");
      out.write("    $('#show-me').css('display', ($(this).val() === 'animal') ? 'inline':'none');\r\n");
      out.write("});\r\n");
      out.write("$(\"input[id='animal-dog']\").click(function () {\r\n");
      out.write("    $('#show-me').css('display', ($(this).val() === 'animal') ? 'inline':'none');\r\n");
      out.write("});\r\n");
      out.write("$(\"input[id='animal-cat']\").click(function () {\r\n");
      out.write("    $('#show-me').css('display', ($(this).val() === 'animal') ? 'inline':'none');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function goList() {\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/board/parcelout/parceloutList\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function parceloutValidate(){\r\n");
      out.write("\tvar content = $(\"[name=parceloutContent]\").val();\r\n");
      out.write("\tif(content.trim().length == 0){\r\n");
      out.write("\t\talert(\"내용을 입력하세요.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"select[name^=sido]\").val()==\"시/도 선택\"){\r\n");
      out.write("\t\talert(\"지역을 선택하세요.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function previewImage(targetObj, View_area) {\r\n");
      out.write("\tvar preview = document.getElementById(View_area); //div id\r\n");
      out.write("\tvar ua = window.navigator.userAgent;\r\n");
      out.write("\t\r\n");
      out.write("\tpreview.style.position = 'relative'; \r\n");
      out.write("\tpreview.style.width = '100px'; \r\n");
      out.write("\tpreview.style.height = '100px';\r\n");
      out.write("\tpreview.style.color = 'black'; \r\n");
      out.write("\tpreview.style.border = '0px solid black'; \r\n");
      out.write("\tpreview.style.display = 'inline';\r\n");
      out.write("\r\n");
      out.write("  //ie일때(IE8 이하에서만 작동)\r\n");
      out.write("\tif (ua.indexOf(\"MSIE\") > -1) {\r\n");
      out.write("\t\ttargetObj.select();\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\tvar src = document.selection.createRange().text; // get file full path(IE9, IE10에서 사용 불가)\r\n");
      out.write("\t\t\tvar ie_preview_error = document.getElementById(\"ie_preview_error_\" + View_area);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (ie_preview_error) {\r\n");
      out.write("\t\t\t\tpreview.removeChild(ie_preview_error); //error가 있으면 delete\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar img = document.getElementById(View_area); //이미지가 뿌려질 곳\r\n");
      out.write("\r\n");
      out.write("\t\t\t//이미지 로딩, sizingMethod는 div에 맞춰서 사이즈를 자동조절 하는 역할\r\n");
      out.write("\t\t\timg.style.filter = \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='\"+src+\"', sizingMethod='scale')\";\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t\tif (!document.getElementById(\"ie_preview_error_\" + View_area)) {\r\n");
      out.write("\t\t\t\tvar info = document.createElement(\"<p>\");\r\n");
      out.write("\t\t\t\tinfo.id = \"ie_preview_error_\" + View_area;\r\n");
      out.write("\t\t\t\tinfo.innerHTML = e.name;\r\n");
      out.write("\t\t\t\tpreview.insertBefore(info, null);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("  //ie가 아닐때(크롬, 사파리, FF)\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tvar files = targetObj.files;\r\n");
      out.write("\t\tfor ( var i = 0; i < files.length; i++) {\r\n");
      out.write("\t\t\tvar file = files[i];\r\n");
      out.write("\t\t\tvar imageType = /image.*/; //이미지 파일일경우만.. 뿌려준다.\r\n");
      out.write("\t\t\tif (!file.type.match(imageType))\r\n");
      out.write("\t\t\t\tcontinue;\r\n");
      out.write("\t\t\tvar prevImg = document.getElementById(\"prev_\" + View_area); //이전에 미리보기가 있다면 삭제\r\n");
      out.write("\t\t\tif (prevImg) {\r\n");
      out.write("\t\t\t\tpreview.removeChild(prevImg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar img = document.createElement(\"img\"); \r\n");
      out.write("\t\t\timg.id = \"prev_\" + View_area;\r\n");
      out.write("\t\t\timg.classList.add(\"obj\");\r\n");
      out.write("\t\t\timg.file = file;\r\n");
      out.write("\t\t\timg.style.width = '100px'; \r\n");
      out.write("\t\t\timg.style.height = '100px';\r\n");
      out.write("\t\t\tpreview.appendChild(img);\r\n");
      out.write("\t\t\tif (window.FileReader) { // FireFox, Chrome, Opera 확인.\r\n");
      out.write("\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\treader.onloadend = (function(aImg) {\r\n");
      out.write("\t\t\t\t\treturn function(e) {\r\n");
      out.write("\t\t\t\t\t\taImg.src = e.target.result;\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t})(img);\r\n");
      out.write("\t\t\t\treader.readAsDataURL(file);\r\n");
      out.write("\t\t\t} else { // safari is not supported FileReader\r\n");
      out.write("\t\t\t\t//alert('not supported FileReader');\r\n");
      out.write("\t\t\t\tif (!document.getElementById(\"sfr_preview_error_\"\r\n");
      out.write("\t\t\t\t\t\t+ View_area)) {\r\n");
      out.write("\t\t\t\t\tvar info = document.createElement(\"p\");\r\n");
      out.write("\t\t\t\t\tinfo.id = \"sfr_preview_error_\" + View_area;\r\n");
      out.write("\t\t\t\t\tinfo.innerHTML = \"not supported FileReader\";\r\n");
      out.write("\t\t\t\t\tpreview.insertBefore(info, null);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var cnt = 0;\r\n");
      out.write("attachFile = {\r\n");
      out.write("        idx:0,\r\n");
      out.write("        add:function(){ // 파일필드 추가\r\n");
      out.write("        \tif(cnt>1){\r\n");
      out.write("        \t\talert(\"사진은 세장까지만 추가가 가능합니다.\")\r\n");
      out.write("        \t\treturn;\r\n");
      out.write("        \t}\r\n");
      out.write("        \tcnt = cnt+1;\r\n");
      out.write("            var o = this;\r\n");
      out.write("            var idx = o.idx;\r\n");
      out.write("\r\n");
      out.write("            var div = document.createElement('div');\r\n");
      out.write("            div.style.marginTop = '3px';\r\n");
      out.write("            div.id = 'file' + o.idx;\r\n");
      out.write("\r\n");
      out.write("            var dv = document.createElement('dv');\r\n");
      out.write("            dv.style.marginTop = '3px';\r\n");
      out.write("            dv.id = 'dv' + o.idx;\r\n");
      out.write("\r\n");
      out.write("            var file = document.all ? document.createElement('<input name=\"upFile\"+cnt>') : document.createElement('input');\r\n");
      out.write("            file.type = 'file';\r\n");
      out.write("            file.name = 'upFile'+cnt;\r\n");
      out.write("            file.size = '40';\r\n");
      out.write("            file.id = 'fileField' + o.idx;\r\n");
      out.write("            file.onchange = function(){o.prev(this,'dv'+idx)};\r\n");
      out.write("\r\n");
      out.write("            var btn = document.createElement('input');\r\n");
      out.write("            btn.type = 'button';\r\n");
      out.write("            btn.value = '삭제';\r\n");
      out.write("            btn.onclick = function(){o.del(idx)};\r\n");
      out.write("            btn.style.marginLeft = '5px';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            div.appendChild(file);\r\n");
      out.write("            div.appendChild(btn);\r\n");
      out.write("            document.getElementById('attachFileDiv').appendChild(div);\r\n");
      out.write("                        document.getElementById('attachFileDiv').appendChild(dv);\r\n");
      out.write("\r\n");
      out.write("            o.idx++;\r\n");
      out.write("        },\r\n");
      out.write("        del:function(idx){ // 파일필드 삭제\r\n");
      out.write("            if(document.getElementById('fileField' + idx).value != '' && !confirm('삭제 하시겠습니까?')){\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            document.getElementById('attachFileDiv').removeChild(document.getElementById('file' + idx));\r\n");
      out.write("                        document.getElementById('attachFileDiv').removeChild(document.getElementById('dv' + idx));\r\n");
      out.write("        },\r\n");
      out.write("        prev:function(targetObj,View_area){ // 이미지 미리보기\r\n");
      out.write("            var preview = document.getElementById(View_area); //div id\r\n");
      out.write("            /* alert(View_area); */\r\n");
      out.write("           var ua = window.navigator.userAgent;\r\n");
      out.write("  //ie일때(IE8 이하에서만 작동)\r\n");
      out.write("    if (ua.indexOf(\"MSIE\") > -1) {\r\n");
      out.write("        targetObj.select();\r\n");
      out.write("        try {\r\n");
      out.write("            var src = document.selection.createRange().text; // get file full path(IE9, IE10에서 사용 불가)\r\n");
      out.write("            var ie_preview_error = document.getElementById(\"ie_preview_error_\" + View_area);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            if (ie_preview_error) {\r\n");
      out.write("                preview.removeChild(ie_preview_error); //error가 있으면 delete\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var img = document.getElementById(View_area); //이미지가 뿌려질 곳\r\n");
      out.write("\r\n");
      out.write("            //이미지 로딩, sizingMethod는 div에 맞춰서 사이즈를 자동조절 하는 역할\r\n");
      out.write("            img.style.filter = \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='\"+src+\"', sizingMethod='scale')\";\r\n");
      out.write("        } catch (e) {\r\n");
      out.write("            if (!document.getElementById(\"ie_preview_error_\" + View_area)) {\r\n");
      out.write("                var info = document.createElement(\"<p>\");\r\n");
      out.write("                info.id = \"ie_preview_error_\" + View_area;\r\n");
      out.write("                info.innerHTML = e.name;\r\n");
      out.write("                preview.insertBefore(info, null);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("  //ie가 아닐때(크롬, 사파리, FF)\r\n");
      out.write("    } else {\r\n");
      out.write("        var files = targetObj.files;\r\n");
      out.write("        for ( var i = 0; i < files.length; i++) {\r\n");
      out.write("            var file = files[i];\r\n");
      out.write("            var imageType = /image.*/; //이미지 파일일경우만.. 뿌려준다.\r\n");
      out.write("            var prevImg = document.getElementById(\"prev_\" + View_area);\r\n");
      out.write("            if (!file.type.match(imageType)){\r\n");
      out.write("                preview.removeChild(prevImg);\r\n");
      out.write("                continue;\r\n");
      out.write("                }\r\n");
      out.write("             //이전에 미리보기가 있다면 삭제\r\n");
      out.write("            if (prevImg) {\r\n");
      out.write("                preview.removeChild(prevImg);\r\n");
      out.write("            }\r\n");
      out.write("            var img = document.createElement(\"img\"); \r\n");
      out.write("            img.id = \"prev_\" + View_area;\r\n");
      out.write("            img.classList.add(\"obj\");\r\n");
      out.write("            img.file = file;\r\n");
      out.write("            img.style.width = '100px'; \r\n");
      out.write("            img.style.height = '100px';\r\n");
      out.write("            preview.appendChild(img);\r\n");
      out.write("            if (window.FileReader) { // FireFox, Chrome, Opera 확인.\r\n");
      out.write("                var reader = new FileReader();\r\n");
      out.write("                reader.onloadend = (function(aImg) {\r\n");
      out.write("                    return function(e) {\r\n");
      out.write("                        aImg.src = e.target.result;\r\n");
      out.write("                    };\r\n");
      out.write("                })(img);\r\n");
      out.write("                reader.readAsDataURL(file);\r\n");
      out.write("            } else { // safari is not supported FileReader\r\n");
      out.write("                //alert('not supported FileReader');\r\n");
      out.write("                if (!document.getElementById(\"sfr_preview_error_\"\r\n");
      out.write("                        + View_area)) {\r\n");
      out.write("                    var info = document.createElement(\"p\");\r\n");
      out.write("                    info.id = \"sfr_preview_error_\" + View_area;\r\n");
      out.write("                    info.innerHTML = \"not supported FileReader\";\r\n");
      out.write("                    preview.insertBefore(info, null);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\t\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t​\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<div class=\"footerInfo\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/common/footer/foot_logo.png\" alt=\"로고\">\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div class=\"footer_txt\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>Team PINKPAW</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>         \r\n");
      out.write("         \t\t\t\t ⓒ핑크포우제공/데이터 출처 <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/common/footer/maf.png\" /> 농림축산식품부 <br />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t핑크포우는 사람과 동물 모두가 행복한 세상을 만들어갑니다.\r\n");
      out.write("\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t핑크포우는 정부나 보호소와는 관련이 없습니다.\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<br>ⓒCOPY RIGHT©2019 PinkPawTeam. ALL RIGHTS RESERVED.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- <style>\r\n");
      out.write("/* footer {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tpadding: 60px;\r\n");
      out.write("\tbackground-color: #394141;\r\n");
      out.write("\tcolor: #7c8c8c;\r\n");
      out.write("\tbottom: 0%\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("footer p:nth-child(2) {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer p:nth-child(3) {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".underline {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer h4 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-family: \"Arial\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
