/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-16 07:18:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pinkpaw.member.model.vo.Member;

public final class termsOfService_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1565937889704L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1565594019433L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pinkpaw.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
 
//로그인성공후 session객체에 저장된 memberLoggedIn가져오기
Member memberLoggedIn
	= (Member)session.getAttribute("memberLoggedIn");
System.out.println("memberLoggedIn@index.jsp="+memberLoggedIn);
/*  memberLoggedIn = new Member();
memberLoggedIn.setMemberId("admin");
 */
System.out.println("memberLoggedIn@index.jsp="+memberLoggedIn);
int recvCount = 0;
if(session.getAttribute("recvCount")!=null){
		recvCount = (int)session.getAttribute("recvCount");
}
System.out.println("memberLoggedIn@index.jsp="+memberLoggedIn); 

//쿠키관련 처리
Cookie[] cookies = request.getCookies();
boolean saveId = false;
String memberId = "";

if(cookies != null){
	System.out.println("-------------------------");
	for(Cookie c: cookies){
		String key = c.getName();
		String value = c.getValue();
		System.out.println(key+" : "+value);
		
		//전송된 saveId쿠키가 있는 경우
		if("saveId".equals(key)){
			saveId = true;
			memberId = value;
		}
	}
	System.out.println("-------------------------");
}




	

      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PinkPaw</title>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--<link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">-->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,target-densitydpi=medium-dpi\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/reset.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/Font.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/Swiper.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-migrate-3.0.0.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/swiper.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.mousewheel.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Noto+Sans|Noto+Sans+KR:100,300,400,500,700,900\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function register(){\r\n");
      out.write("\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/member/termsOfService\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(()=>{\r\n");
      out.write("\tvar host = location.host;\r\n");
      out.write("\tvar ws = new WebSocket('ws://'+host+\"");
      out.print(request.getContextPath());
      out.write("/chat/helloWebSocket\");\r\n");
      out.write("\t\r\n");
      out.write("\t//최초연결시 open이벤트 핸들러\r\n");
      out.write("\tws.onopen = e => {\r\n");
      out.write("\t\tconsole.log(\"ws open!\");\r\n");
      out.write("\t};\r\n");
      out.write("\t//서버로부터 message를 전달 받았을 때 핸들러\r\n");
      out.write("\tws.onmessage = e => {\r\n");
      out.write("\t\t//console.log(\"ws message: \"+e.data);\r\n");
      out.write("\t\tvar o = JSON.parse(e.data);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//타입 메세지 처리\r\n");
      out.write("\t\tif(o.type === 'message'){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar html = \"<li class='list-group-item'>\";\r\n");
      out.write("\t\t\thtml += \"<span class='badge badge-dark'>\"+o.sender+\"</span>\";\r\n");
      out.write("\t\t\thtml += \"&nbsp;&nbsp;\"+o.msg;\r\n");
      out.write("\t\t\thtml += \"</li>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#msg-container ul\").append(html);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//scroll처리\r\n");
      out.write("\t\t\tvar scrollHeight = $(\"#msg-container\").prop(\"scrollHeight\");\r\n");
      out.write("\t\t\t//console.log(scrollHeight);\r\n");
      out.write("\t\t\t$(\"#msg-container\").scrollTop(scrollHeight);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(o.type === \"dm\"){\r\n");
      out.write("\t\t\talert(\"쪽지가 도착했습니다\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t//서버처리 도중 error발생시 핸들러\r\n");
      out.write("\tws.onerror = e =>{\r\n");
      out.write("\t\tconsole.log(\"ws error!\");\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t//서버와 연결 종료시 핸들러\r\n");
      out.write("\tws.onclose = e =>{\r\n");
      out.write("\t\tconsole.log(\"ws close!\");\t\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validate(){\r\n");
      out.write("\tif($(\"#memberId\").val().trim().length == 0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif($(\"#password\").val().trim().length == 0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#password\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--header-->\r\n");
      out.write("\t<div class=\"headerWrap\">\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/main/logo_white.png\" alt=\"logo\"></a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("​\r\n");
      out.write("\t\t\t$('.headerWrap').mouseover(function(e){\r\n");
      out.write("\t\t\t\t$(this).css('background','rgba(34,34,34,0.7)');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('.headerWrap').mouseout(function(e){\r\n");
      out.write("\t\t\t\t$(this).css('background','none');}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("​\r\n");
      out.write("\t\t\t$('header>div>ul:first-child>li').mouseover(function(e){\r\n");
      out.write("\t\t\t\t$('.headerWrap').css('height','140px');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t$('header>div>ul:first-child>li').mouseout(function(e){\r\n");
      out.write("\t\t\t\t$('.headerWrap').css('height','84px');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t​ <a href=\"#none\" onClick=\"$('.menuWrap').fadeIn(300);\"><img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/images/main/icon_meun.png\" alt=\"메뉴바\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t​ ​\r\n");
      out.write("\t<!--menu-->\r\n");
      out.write("\t<div class=\"menuWrap\">\r\n");
      out.write("\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t<a href=\"#none\" onClick=\"$('.menuWrap').fadeOut(300);\"\r\n");
      out.write("\t\t\t\tclass=\"menu_closeBtn\"><img src=\"images/main/modal_close.gif\"\r\n");
      out.write("\t\t\t\talt=\"닫기\"></a>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 if(memberLoggedIn == null){ 
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" \r\n");
      out.write("\t\t\t\t\t  id=\"loginFrm\"\r\n");
      out.write("\t\t\t\t\t  method=\"post\"\r\n");
      out.write("\t\t\t\t\t  onsubmit=\"return validate();\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   placeholder=\"아이디\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"1\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   value=\"");
      out.print(saveId?memberId:"");
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"로그인\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"3\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"password\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   placeholder=\"비밀번호\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   tabindex=\"2\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   name=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   id=\"saveId\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   ");
      out.print(saveId?"checked":"");
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"saveId\">아이디저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   value=\"회원가입\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   onclick=\"register();\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t");
 } 
			//로그인에 성공한 경우
			else {
      out.write("\t\r\n");
      out.write("\t\t\t\t<table id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(memberLoggedIn.getMemberName() );
      out.write("님, 안녕하세요.\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"쪽지:");
      out.print(recvCount );
      out.write("개\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/board/dm/dmView\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"신고쪽지\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/board/dm/reportDMList'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"신고게시판\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/reportBoardList'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t   \t   \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"마이페이지\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberView?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"내가쓴글보기\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myBoard'\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t   <input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"내가쓴댓글보기\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/myComment'\"/>\t   \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"로그아웃\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");
 } 
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/notice/noticeBoardList\">공지사항</a>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt class=\"sub_menu\">유기동물</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/organic/graph/OrganicGraph\">유기동물 통계</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/animal/animalNotice\">유기동물 공고</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl class=\"ddSize\">\r\n");
      out.write("\t\t\t\t<dt class=\"sub_menu\">보호소</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/shelter/shelterList\">보호소 찾기</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/volunteer/volunteerList\">보호소 봉사요청</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt class=\"sub_menu\">커뮤니티</dt>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/missingList\">실종동물</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/parcelout/parceloutList\">분양동물</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/review/reviewList\">후기</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/board/community/free/freeList\">자유게시판</a>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t");
if(memberLoggedIn!=null && "admin".equals(memberLoggedIn.getMemberId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\">회원리스트</a>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(()=>{\r\n");
      out.write("\t\t\t$(\".sub_menu\").on(\"click\", function(e){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).parent().siblings().children(\"dd\").css('display','none');\r\n");
      out.write("\t\t\t\t$(this).siblings().css('display','inline-block');\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>​\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--menu end-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--header end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2>회원가입 약관</h2>\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("\r\n");
      out.write(" <div style=\"overflow:scroll; width:400px; height: 500px;\">\r\n");
      out.write(" \r\n");
      out.write("제1조(목적)\r\n");
      out.write("이 약관은 유기견보호센터(이하 회사)이 운영하는 사이트 유기견보호센터 www.zooseyo.or.kr\r\n");
      out.write("(이하 “ 유기견보호센터”라 한다)에서 제공하는 인터넷 관련 서비스를 이용함에 있어 이를 이용하는\r\n");
      out.write("이용자와 유기견보호센터의 권리·의무 및 책임사항을 규정함을 목적으로 한다.\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제2조 (용어의 정의)\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("이 약관에서 사용하는 용어의 정의는 아래와 같다. \r\n");
      out.write("① 회사 라 함은 인터넷 사이트 유기견보호센터 www.zooseyo.or.kr 을 운영하는 유기견보호센터을 말한다.\r\n");
      out.write("② 서비스 라 함은 인터넷 유기견보호센터 www.zooseyo.or.kr 및 정보통신설비등을 이용하여 유기견보호센터가 회원들이 애견분양(구매,판매)을 목적으로 등록하는 자료등을 각각의 목적에 맞게 분류, 가공하여 정보를 제공하는 내용 및 기타 관련된 서비스를 말한다.\r\n");
      out.write("③ 회원 이라 함은 애견분양(판매, 구매)을 목적으로 서비스를 이용하기 위하여 동 약관에 동의하여 이용자 ID를 부여받은 사람을 말한다.\r\n");
      out.write("④ 이용자ID 또는 \\\"회원ID\\\"라 함은 회원의 식별과 회원의 서비스 이용을 위하여 회원이 선정하고 부여하는 문자와 숫자의 조합을 말한다. \r\n");
      out.write("⑤ 비밀번호라 함은 회사의 서비스를 이용하려는 사람이 이용자ID를 부여받은 자와 동일인임을 확인하고 회원의 권익을 보호하기 위하여 회원이 선정한 문자와 숫자의 조합을 말한다.\r\n");
      out.write("<br />\r\n");
      out.write("제3조 (약관의 효력 및 개정)\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("1. 이 약관은 인터넷 사이트 유기견보호센터을 통하여 이를 공지하거나 전자우편 기타의 방법으로 회원에게 통지함으로써 효력이 발생됩니다. \r\n");
      out.write("2. 회사는 관련법규를 준수하는 범위내에서 이 약관을 개정할 수 있으며, 사정상 중요한 사유가 발생될 경우 사전 고지 없이 이 약관의 내용을 변경할 수 있으며, 변경된 약관은 제1항과 같은 방법으로 공지 또는 통지함으로써 효력이 발생됩니다. \r\n");
      out.write("3. 회원은 변경된 약관에 동의하지 않을 경우 회원 탈퇴를 요청할 수 있으며, 변경된 약관의 효력 발생일 이후에도 서비스를 계속 사용할 경우 약관의 변경 사항에 동의한 것으로 간주됩니다. \r\n");
      out.write("4. 회사는 이 약관의 내용과 상호, 영업장 소재지, 대표자의 성명, 사업자등록번호, 연락처 등을 이용자가 알 수 있도록 게시하거나 기타의 방법으로 이용자에게 공지해야 한다.\r\n");
      out.write("<br />\r\n");
      out.write("제4조 (약관 외 준칙)\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("이 약관에서 규정하지 않은 사항에 관해서는 전기통신기본법, 전기통신사업법, 정보통신망 이용촉진등에 관한 법률, 전자거래기본법, 신용정보이용및보호에관한법률, 기타 관련 법령의 규정에 따릅니다.\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제5조 (이용신청의 승낙과 제한)\r\n");
      out.write("<br />\r\n");
      out.write("① 회사는 이용신청자의 처리를 특별한 경우를 제외하고는 접수순서에 따라 서비스 이용을 승낙하는것을 원칙으로한다. \r\n");
      out.write("② 회사는 다음 각 호의 1에 해당하는 이용계약 신청에 대하여는 이를 승낙하지 아니 할 수 있습니다. \r\n");
      out.write("1. 본인의 실명, 또는 개인정보를 정확히 기재하지 않는 경우\r\n");
      out.write("2. 다른 사람의 명의를 도용하여 신청한 경우\r\n");
      out.write("3. 기재된 내용중 허위로 기재하여 신청한 경우\r\n");
      out.write("4. 현행법규에 위배되는 내용이나 사회의 미풍양속을 저해할 목적으로 신청한 경우\r\n");
      out.write("5. 회원자격을 상실한 적이 있는 회원\r\n");
      out.write("6. 기타 회사가 서비스운영상 필요하다고 인정되거나, 업무에 문제가 있다고 판단되는 경우\r\n");
      out.write("<br />\r\n");
      out.write("③ 회사는 아래 사항에 해당하는 경우에는 그 신청에 대하여 승낙을 유보할 수 있다. \r\n");
      out.write("1. 회사가 설비의 여유가 없는 경우 \r\n");
      out.write("2. 회사의 기술상 지장이 있는 경우 \r\n");
      out.write("3. 기타 회사의 사정상 필요하다고 인정되는 경우\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제6조 (이용계약의 성립)\r\n");
      out.write("<br />\r\n");
      out.write("① 유기견보호센터가 제공하는 서비스를 받고자 하는 자는 회원가입절차를 거쳐 회원으로 가입하여야 하며, 회원 가입희망자가 이 약관의 내용을 동의하고, 이용신청에 대하여 회사가 승낙함으로써 성립한다.\r\n");
      out.write("② 제1항의 승낙은 이용신청자의 본 약관에 대한 동의를 확인하고 전자메일의 매체를 통하여 통지함으로써 이용계약이 성립한다. \r\n");
      out.write("③ 서비스를 이용하고자 하는 자가 이용신청 당시 웹상의 \\\"동의함\\\" 버튼을 누르면 본 약관 및 개인정보보호정책에 대하여도 동의한 것으로 간주한다.\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제7조 (서비스 이용신청)\r\n");
      out.write("<br />\r\n");
      out.write("① 회원으로 가입하여 본 서비스를 이용하고자 하는 이용고객은 회사에서 요구하는 제반정보를 가입신청 양식에 기록해 주어야 한다. \r\n");
      out.write("② 모든 회원은 제1항의 기입한 내용에 하자가 없어야만 서비스를 이용할 수 있으며, 기재내용이 허위로 등록된 경우에는 서비스 사용에대한 제한을 받을수 있을뿐만아니라, 사용자는 일체의 권리를 주장할 수 없다. \r\n");
      out.write("③ 타인의 명의를 도용하여 이용신청을 한 회원의 모든 ID는 삭제되며, 관계법령에 따라 처벌을 받을 수 있다.\r\n");
      out.write("<br />\r\n");
      out.write("제3장 서비스 이용\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제8조 (서비스의 내용)\r\n");
      out.write("<br />\r\n");
      out.write("① 회사는 제2조 1항의 서비스를 제공할 수 있으며 그 내용은 다음 각 호와 같다. \r\n");
      out.write("1. 분양공고 서비스(일반분양, 긴급분양)\r\n");
      out.write("2. 분양공고 스크랩\r\n");
      out.write("3. 기타 애견과 관련된 제반 서비스\r\n");
      out.write("② 회사는 필요한 경우 서비스의 내용을 추가 또는 변경할 수 있다. \r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제9조 (정보의 제공) \r\n");
      out.write("회사는 회원이 서비스 이용중 필요가 있다고 인정되는 다양한 정보를 공지사항이나 전자우편 등의 방법으로 회원에게 제공할 수 있습니다. \r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("제10조 (회원의 의무)\r\n");
      out.write("<br /><br />\r\n");
      out.write("<br />\r\n");
      out.write("① 회원은 관계법령과 본 약관의 규정 및 기타 회사가 공지, 통지하는 사항을 준수하여야 하며, 기타 회사의 업무에 방해되는 행위를 해서는 안 된다. \r\n");
      out.write("② 회원은 회원에게 부여된 ID와 비밀번호의 관리 소홀, 부정사용에 의하여 발생하는 모든 결과에 대한 책임은 회원에게 있습니다. \r\n");
      out.write("③ 회원은 자신의 ID나 비밀번호가 부정하게 사용되었다는 사실을 발견한 경우에는 즉시 회사에 알려야 하며, 알리지 않아 발생하는 모든 결과에 대한 책임은 회원에게 있습니다. \r\n");
      out.write("④ 회원은 회사가 공지사항에 게시하거나 별도로 공지한 이용제한 사항을 준수하여야 한다.\r\n");
      out.write("⑤ 회원은 회사의 사전승낙 없이는 서비스를 이용하여 영업활동을 할 수 없으며, 그 영업활동의 결과와 회원이 약관에 위반한 영업활동을 하여 발생한 결과에 대하여 회사는 책임을 지지 않는다. 회원은 이와 같은 영업활동으로 회사에 손해를 입은 경우 회원은 회사에 대하여 손해배상의무를 진다.\r\n");
      out.write("⑥ 회원은 회사의 명시적인 동의가 없는 한 서비스의 이용권한, 기타 이용계약상 지위를 타인에게 양도, 증여할 수 없으며, 이를 담보로 제공할 수 없다. \r\n");
      out.write("⑤ 회원은 본 서비스를 건전한 서비스이용 이외의 목적으로 사용해서는 안되며 이용 중 다음 각 호의 행위를 해서는 안 된다. \r\n");
      out.write("1. 범죄행위을 목적으로 하거나 기타 범죄행위와 관련된 행위 \r\n");
      out.write("2. 공공질서 및 미풍양속에 위반되는 내용등을 전송, 게시, 전자메일 또는 기타의 방법으로 타인에게 유포하는 행위 \r\n");
      out.write("3. 다른 회원의 ID와 비밀번호, 개인식별정보 등을 도용하는 행위 \r\n");
      out.write("4. 회사의 직원이나 관리자를 가장하거나 사칭하여 내용물을 게시, 등록하거나 메일을 발송하는 행위 \r\n");
      out.write("5. 타인의 명예를 훼손하거나 모욕하는 행위 \r\n");
      out.write("6. 타인의 지적재산권 등의 권리를 침해하는 행위 \r\n");
      out.write("7. 해킹행위 또는 바이러스의 유포 행위 \r\n");
      out.write("8. 타인의 의사에 반하여 광고성 정보 등 일정한 내용을 계속적으로 전송하는 행위\r\n");
      out.write("9. 서비스의 안정적인 운영에 지장을 주거나 줄 우려가 있다고 판단되는 행위 \r\n");
      out.write("10. 사이트의 정보 및 서비스를 이용한 영리 행위 \r\n");
      out.write("11. 그밖에 선량한 풍속, 기타 사회질서를 해하거나 관계법령에 위반하는 행위\r\n");
      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("<< 부칙 >>\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("제1조 (판매자 등급평가 및 신용점수 기준)\r\n");
      out.write("<br />\r\n");
      out.write("<br />\r\n");
      out.write("①유기견보호센터 점수별 등급부여는 다음과 같다.<br />\r\n");
      out.write("1.신용점수가 마이너스인 회원은 최저등급이 부여된다.<br />\r\n");
      out.write("2.신용점수가 100점~ 1,000점인 회원은 일반등급이 부여된다.<br />\r\n");
      out.write("3.신용점수가 1,001점~ 5,000점인 회원은 믿음등급이 부여된다.<br />\r\n");
      out.write("4.신용점수가 5,001점 이상인 상위 10명회원 또는 관리자가 승인한 회원에게 안심등급이 부여된다.<br />\r\n");
      out.write("\r\n");
      out.write("②유기견보호센터싸이트에 가입한 경우에는 초기 신용점수 100점이 부여된다.<br />\r\n");
      out.write("③유기견보호센터싸이트에 로그인 할 경우 1일 1회에 한해 신용점수 5점이 부여된다.<br />\r\n");
      out.write("④유료분양글을 등록하는 경우에만 글 등록 당 신용점수 10점이 부여된다.<br />\r\n");
      out.write("1.유료분양글 등록은 일일 제한없이 등록할 수 있다.<br />\r\n");
      out.write("2.무료분양글(무료로드림, 무료로주세요)을 등록하는 경우에는 신용점수가 부여되지 않는다.<br />\r\n");
      out.write("<br />\r\n");
      out.write("⑤안심분양을 등록후 분양완료한 경우 추가로 신용점수 200점이 부여된다.<br />\r\n");
      out.write("⑥애견분양시 매매계약서를 미교부할 경우 미교부건당 신용점수 -50점이 차감된다.\r\n");
      out.write("1.자료가 확실한 경우에만 적용\r\n");
      out.write("<br />\r\n");
      out.write("⑦애견분양후 피해사례가 신고되는 경우 신고건당 신용점수 -50점이 차감된다.<br />\r\n");
      out.write("1.애견분양후 피해사례를 입증할 자료가 확실한 경우\r\n");
      out.write("2.애견분양후 피해사례를 판매자가 처리해 주지 않는 경우\r\n");
      out.write("<br />\r\n");
      out.write("⑧애견분양후 피해사례가 일정기간동안 다수 신고되는 경우 사전통보 없이, 해당 \r\n");
      out.write("판매자아이디를 이용정지 처리를 할 수 있으며, 신용점수를 차감할 수 있다.<br />\r\n");
      out.write("1.일주일에 5건이상 피해접수 또는 한달 10건이상 피해접수와 같이 비정상적인 피해신고접수가 되는 경우\r\n");
      out.write("<br />\r\n");
      out.write("⑨애견분양후 애견피해사례건으로 경찰서에 신고접수 되는 경우 해당 판매자를 \r\n");
      out.write("사전통보 없이 사건해결전까지 이용정지처리 할수 있다.<br />\r\n");
      out.write("⑩안심분양만 이용하시는 오프라인 매장 사업자님의 경우 [안심등급 신청하기]를 \r\n");
      out.write("신청하시면 기존의 신용점수와 상관없이 관리자의 승인후 기존의 신용점수는 유지되며,\r\n");
      out.write("안심등급을 부여받을 수 있다.\r\n");
      out.write("1.안심분양후 피해사례가 발생시 관리자의 판단하에 기존의 등급으로 조정할 수 있다.\r\n");
      out.write("\r\n");
      out.write("⑪그외 기타 사이트 내 활동에 의거하여 이용정지 및 신용점수가 차감되거나 부여될수 있다.\r\n");
      out.write("<br /><br /><br />\r\n");
      out.write("제2조 (유기견보호센터&캣조아 서비스 통합안내) \r\n");
      out.write("1.유기견보호센터와 캣조아 서비스 통합은 다음과 같다.\r\n");
      out.write("①.유기견보호센터의 회원은 별도의 가입절차 없이 기존의 아이디, 비밀번호로 캣조아 사이트의 서비스를 이용할 수 있다. \r\n");
      out.write("②.유기견보호센터에서 보유한 뼈다귀(사이버머니)는 캣조아에서도 동일하게 사용이 가능하다. \r\n");
      out.write("③.뼈다귀 사용현황, 나의 판매등급관리, 등록한 무료분양글 관리, 스크랩한 분양글 보기, 1:1문의게시판, 회원정보수정 및 탈퇴신청, 펫도우미, 무료분양글 서비스는 캣조아와 통합적으로 서비스를 이용할 수 있다.\r\n");
      out.write("<br /><br /><br />\r\n");
      out.write("(시행일) 이 부칙은 2008년 9월 22일부터 시행한다.\r\n");
      out.write(" \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <br /><br /><br />\r\n");
      out.write(" \r\n");
      out.write(" <h2>개인정보 취급방침</h2>\r\n");
      out.write(" \r\n");
      out.write(" <br />\r\n");
      out.write(" <br />\r\n");
      out.write(" <br />\r\n");
      out.write(" \r\n");
      out.write("<div style=\"overflow:scroll; width:400px; height: 500px;\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("1.개인정보의 수집목적 및 이용목적 \r\n");
      out.write("① 유기견 보호센터는 회원님께 최대한으로 최적화되고 맞춤화된 서비스를 제공하기 위하여 다음과 같은 목적으로 개인정보를 수집하고 있습니다. \r\n");
      out.write("- 성명, 아이디, 비밀번호 : 회원제 서비스 이용에 따른 본인 식별 절차에 이용\r\n");
      out.write("- 이메일주소, 이메일 수신여부, 전화번호 : 고지사항 전달, 본인 의사 확인, 불만 처리 등 원활한 의사소통 경로의 확보, 새로운 서비스/신상품이나 이벤트 정보의 안내 \r\n");
      out.write("- 주소, 전화번호 : 경품과 쇼핑 물품 배송에 대한 정확한 배송지의 확보 \r\n");
      out.write("- 비밀번호 힌트용 질문과 답변 : 비밀번호를 잊은 경우의 신속한 처리를 위한 내용 \r\n");
      out.write("- 그 외 선택항목 : 개인맞춤 서비스를 제공하기 위한 자료 \r\n");
      out.write("② 단, 이용자의 기본적 인권 침해의 우려가 있는 민감한 개인정보(인종 및 민족, 사상 및 신조, 출신지 및 본 적지, 정치적 성향 및 범죄기록, 건강상태 및 성생활 등)는 수집하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("2.수집하는 개인정보의 항목\r\n");
      out.write("유기견 보호센터는 별도의 회원가입 절차 없이 대부분의 컨텐츠에 자유롭게 접근할 수 있습니다. 유기견 보호센터의 회원제 서비스를 이용하시고자 할 경우 다음의 정보를 입력해주셔야 하며 선택항목을 입력하시지 않았다 하여 서비스 이용에 제한은 없습니다. \r\n");
      out.write("①회원 가입시 수집하는 개인정보의 범위 \r\n");
      out.write("- 필수항목 : 희망 ID, 비밀번호, 비밀번호 힌트용 질문과 답변, 성명, 생년월일, 주소, 전화번호\r\n");
      out.write("- 선택항목 : 이메일주소, 이메일 수신 여부 회사주소\r\n");
      out.write("- 자동수집항목 : IP Address, 서비스 이용기록 등\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("3.개인정보의 보유기간 및 이용기간\r\n");
      out.write("① 귀하의 개인정보는 다음과 같이 개인정보의 수집목적 또는 제공받은 목적이 달성되면 파기됩니다. 단, 상법 등 관련법령의 규정에 의하여 다음과 같이 거래 관련 권리 의무 관계의 확인 등을 이유로 일정기간 보유하여야 할 필요가 있을 경우에는 일정기간 보유합니다. \r\n");
      out.write("- 회원가입정보의 경우, 회원가입을 탈퇴하거나 회원에서 제명된 경우 등 일정한 사전에 보유목적, 기간 및 보유하는 개인정보 항목을 명시하여 동의를 구합니다.\r\n");
      out.write("- 계약 또는 청약철회 등에 관한 기록 : 5년\r\n");
      out.write("- 대금결제 및 재화등의 공급에 관한 기록 : 5년 \r\n");
      out.write("- 소비자의 불만 또는 분쟁처리에 관한 기록 : 3년\r\n");
      out.write("② 귀하의 동의를 받아 보유하고 있는 거래정보 등을 귀하께서 열람을 요구하는 경우 유기견 보호센터는 지체없이 그 열람, 확인 할 수 있도록 조치합니다.\r\n");
      out.write(" \r\n");
      out.write(" </div><br />\r\n");
      out.write(" <br />\r\n");
      out.write(" <br />\r\n");
      out.write("       <input type=\"checkbox\" name=\"agree\" id=\"agree\" /> 회원관리 약관에 동의합니다\r\n");
      out.write("       <br />\r\n");
      out.write("       <br />\r\n");
      out.write("       <br />\r\n");
      out.write("       <br />\r\n");
      out.write("       <br />\r\n");
      out.write("       <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/member/register.jpg\" id=\"click\" style=\"width:200px; height: 150px;\">   \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <script>\r\n");
      out.write(" \r\n");
      out.write(" $(\"#click\").click(function(){\r\n");
      out.write("\t \r\n");
      out.write("\t var bool = $(\"input[name='agree']\").prop(\"checked\");\r\n");
      out.write("\t \r\n");
      out.write("\t if( bool == true){\r\n");
      out.write("\r\n");
      out.write("\t\t location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll\";\r\n");
      out.write("\t }\r\n");
      out.write("\t else{\r\n");
      out.write("\t\t alert(\"약관에 동의 체크를 해주세요\");\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t​\r\n");
      out.write("\t<article>\r\n");
      out.write("\t\t<div class=\"footerInfo\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/common/footer/foot_logo.png\" alt=\"로고\">\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div class=\"footer_txt\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>Team PINKPAW</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>         \r\n");
      out.write("         \t\t\t\t ⓒ핑크포우제공/데이터 출처 <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/common/footer/maf.png\" /> 농림축산식품부 <br />\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t핑크포우는 사람과 동물 모두가 행복한 세상을 만들어갑니다.\r\n");
      out.write("\t\t\t\t\t</li> \r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t핑크포우는 정부나 보호소와는 관련이 없습니다.\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<br>ⓒCOPY RIGHT©2019 PinkPawTeam. ALL RIGHTS RESERVED.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- <style>\r\n");
      out.write("/* footer {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tpadding: 60px;\r\n");
      out.write("\tbackground-color: #394141;\r\n");
      out.write("\tcolor: #7c8c8c;\r\n");
      out.write("\tbottom: 0%\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("footer p:nth-child(2) {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer p:nth-child(3) {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".underline {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer h4 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-family: \"Arial\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style> -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar dWidth=$(window).width();\r\n");
      out.write("\t\tvar dHeight=$(window).height();\r\n");
      out.write("\t\t$('section').css({height:dHeight+'px'});\r\n");
      out.write("\r\n");
      out.write("\t\t//선택되어져 있는 네비게이션 표시\r\n");
      out.write("\t\t$(window).scroll(function(e){\r\n");
      out.write("\t\tvar ht=$(window).height();\r\n");
      out.write("\t\tvar dScroll=$(window).scrollTop();\r\n");
      out.write("\t\tif(dScroll>=0 && dScroll<ht){\r\n");
      out.write("\t\t\t$('nav>ul>li').removeClass('on');\r\n");
      out.write("\t\t\t$('nav>ul>li:nth-child(1)').addClass('on');\r\n");
      out.write("\t\t\t$('.headerWrap').css({'background':'none', 'border-bottom':'none'});\r\n");
      out.write("\t\t\t$('header>h1>a>img').attr('src','");
      out.print(request.getContextPath());
      out.write("/images/main/logo_white.png');\r\n");
      out.write("\t\t\t$('header>div>a>img').attr('src','");
      out.print(request.getContextPath());
      out.write("/images/main/icon_meun.png');\r\n");
      out.write("\t\t\t$('header>div>ul>li>a').css('color','#fff');\r\n");
      out.write("\t\t\t$('.headerWrap').mouseover(function(e){$(this).css('background','rgba(34,34,34,0.7)');});\r\n");
      out.write("\t\t\t$('.headerWrap').mouseout(function(e){$(this).css('background','none');});\r\n");
      out.write("\t\t\t$('header .asideNav').css('background','url(\"images/main/bg_gnbLine.png\") no-repeat left center');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(dScroll>=ht && dScroll<ht*2){\r\n");
      out.write("\t\t\t$('nav>ul>li').removeClass('on');\r\n");
      out.write("\t\t\t$('nav>ul>li:nth-child(2)').addClass('on');\r\n");
      out.write("\t\t\tif(dWidth <= 450){\r\n");
      out.write("\t\t\t\t$('.headerWrap').css({'background':'#fff', 'height':'7%'});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('.headerWrap').css({'background':'#fff', 'height':'84px', 'border-bottom':'1px solid #eee', 'box-sizing':'border-box'});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('header>h1>a>img').attr('src','");
      out.print(request.getContextPath());
      out.write("/images/main/logo_color.png');\r\n");
      out.write("\t\t\t$('header>div>a>img').attr('src','");
      out.print(request.getContextPath());
      out.write("/images/main/icon_meun_black.png');\r\n");
      out.write("\t\t\t$('header>div>ul>li>a').css('color','#222');\r\n");
      out.write("\t\t\t$('.headerWrap').mouseover(function(e){$(this).css('background','#fff');});\r\n");
      out.write("\t\t\t$('.headerWrap').mouseout(function(e){$(this).css('background','#fff');});\r\n");
      out.write("\t\t\t$('header .asideNav').css('background','url(\"images/main/bg_gnbLine_100.png\") no-repeat left center');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(dScroll>=ht*2 && dScroll<ht*3){\r\n");
      out.write("\t\t\t$('nav>ul>li').removeClass('on');\r\n");
      out.write("\t\t\t$('nav>ul>li:nth-child(3)').addClass('on');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(dScroll>=ht*3 && dScroll<ht*4){\r\n");
      out.write("\t\t\t$('nav>ul>li').removeClass('on');\r\n");
      out.write("\t\t\t$('nav>ul>li:nth-child(4)').addClass('on');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//메뉴버튼 클릭시 페이지 이동 이벤트\r\n");
      out.write("\t\t$('nav>ul>li>a').click(function(e){\r\n");
      out.write("\t\t\tvar secPos=$(this).attr('href'); //해당아이디\r\n");
      out.write("\t\t\tvar sec=$(secPos).position().top;  //top의 수치를 가져오기 위함\r\n");
      out.write("\t\t\t$('body,html').stop().animate({scrollTop:sec},1200,'swing');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//마우스 휠 이벤트\r\n");
      out.write("\t\t$('section').on('mousewheel',function(event,delta){\r\n");
      out.write("\t\t\tif(delta>0 && $('#sec02','#sec03','#sec04')){\r\n");
      out.write("\t\t\t\tvar prev=$(this).prev().offset().top;\r\n");
      out.write("\t\t\t\t$('body,html').stop().animate({scrollTop:prev},1200,'swing');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tif(delta<0 && $('#sec01','#sec02','#sec03')){\r\n");
      out.write("\t\t\t\tvar next=$(this).next().offset().top;\r\n");
      out.write("\t\t\t\t$('body,html').stop().animate({scrollTop:next},1200,'swing');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(dWidth <= 767 && $(window).scrollTop() > 0){\r\n");
      out.write("\t\t\t\t$('.headerWrap').css('background','#fff!important');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//header width값 고정\r\n");
      out.write("\t\tif(dWidth < 1024){\r\n");
      out.write("\t\t\t$('header').css('width','1024px');\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t//반응형(모바일)\r\n");
      out.write("\t\tif(dWidth <= 767){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*header*/\r\n");
      out.write("\t\t\t$('.headerWrap').css({'position':'fixed', 'height':'7%!important'});\r\n");
      out.write("\t\t\t$('.headerWrap>header').css('width','100%');\r\n");
      out.write("\t\t\t/*$('header').css({'padding-top':dWidth/100*5, 'margin-left':'0', 'left':'5%', 'height':'auto'});*/\r\n");
      out.write("\t\t\t$('header').css({'padding':'5%', 'margin-left':'0', 'left':'auto', 'height':'auto'});\r\n");
      out.write("\t\t\t$('header>div>ul').hide();\r\n");
      out.write("\t\t\t$('header>h1').css({'margin-top':'0', 'width':'19%'});\r\n");
      out.write("\t\t\t$('header>div').css('width','5.85%');\r\n");
      out.write("\t\t\t$('header>div>a').css({'margin-top':'0', 'margin-left':'0'});\r\n");
      out.write("\t\t\t$('header>div>a').attr('onClick','$(\".menuWrap_m\").fadeIn(300);');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*menu*/\r\n");
      out.write("\t\t\t$('.menuWrap_m>.menu>a').click($(function(){$('#div').hide()})); \r\n");
      out.write("\t\t\t$('.menuWrap_m .menu').css('height',dHeight);\r\n");
      out.write("\t\t\t$('.menuWrap_m .menu>div').css({'padding-top':dWidth/100*5, 'margin-left':'0', 'left':'5%', 'height':'12%', 'box-sizing':'border-box'});\r\n");
      out.write("\t\t\t//$('.menuWrap_m .menu>div').css('padding-bottom',dWidth/100*5);\r\n");
      out.write("\t\t\t$('.menuWrap_m dl>dt').css('padding-top',dWidth/100*5);\r\n");
      out.write("\t\t\t$('.menuWrap_m dl>dt').css('padding-bottom',dWidth/100*5);\r\n");
      out.write("\t\t\t$('.menuWrap_m dl>dd>p').css('padding-top',dWidth/100*5*0.772);\r\n");
      out.write("\t\t\t$('.menuWrap_m dl>dd>p').css('padding-bottom',dWidth/100*5*0.772);\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*sec01*/\r\n");
      out.write("\t\t\t$('#sec01 h1>p').html(\"KG에듀원의 또 다른 이름은<br> 꿈을 이루는 '드림파트너'입니다.\");\r\n");
      out.write("\t\t\t$('#sec01 .btn_magazine>img').attr('src','images/main/btn_magazine_m.png');\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*sec02*/\r\n");
      out.write("\t\t\t$('#sec02 h2').html('KG에듀원의<br>브랜드를 소개합니다.');\r\n");
      out.write("\t\t\t$('#sec02 .brand>li').removeClass('mt50 mt-50');\r\n");
      out.write("\t\t\t$('#sec02 .brand>li>a').height(dWidth/100*28.888);\r\n");
      out.write("\t\t\t$('.brandWrap').removeClass('swiper-container');\r\n");
      out.write("\t\t\t$('.brand').removeClass('swiper-wrapper');\r\n");
      out.write("\t\t\t$('.brand>li').removeClass('swiper-slide');\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*sec03*/\r\n");
      out.write("\t\t\t$('#sec03 h2').html('KG에듀원의 새로운 소식');\r\n");
      out.write("\t\t\t$('#sec03 .swiper-container>ul').addClass('swiper-wrapper');\r\n");
      out.write("\t\t\t$('#sec03 .swiper-container>ul>li').addClass('swiper-slide');\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*sec04*/\r\n");
      out.write("\t\t\t$('#sec04 h2').html('KG에듀원과<br>함께 할 당신을 기다립니다.');\r\n");
      out.write("\t\t\t$('#sec04 .career').height(dWidth/100*28.888);\r\n");
      out.write("\t\t\t$('#sec04 ul>li').removeClass('rightBox');\r\n");
      out.write("\t\t\t$('#sec04 .career>.careerTxt>p').html('자세히보기');\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*sec05*/\r\n");
      out.write("\t\t\t$('#sec05 .noticeWrap>.linkBnr>ul>li').height(dWidth/100*35.533);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
