/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-14 11:24:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.organic.announcement;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import com.pinkpaw.animal.model.vo.ProtectedAnimal;

public final class announcementView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.pinkpaw.animal.model.vo.ProtectedAnimal");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 유기동물 공고 상세보기 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ProtectedAnimal p = (ProtectedAnimal)request.getAttribute("Animal");

	SimpleDateFormat format1  = new SimpleDateFormat("yyyy년 MM월 dd일");
	SimpleDateFormat format2  = new SimpleDateFormat("yyyyMMdd");
	SimpleDateFormat format3  = new SimpleDateFormat("yyyy-MM-dd");
	
	Date d1 = format2.parse(p.getNoticeSdt());
	Date d2 = format2.parse(p.getNoticeEdt());

	Calendar cal = Calendar.getInstance();
	String date1 = format1.format(cal.getTime());
	String d_1 = format3.format(d1);
	String d_2 = format3.format(d2);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" \r\n");
      out.write("integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" \r\n");
      out.write("crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/animal.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"article\">\r\n");
      out.write("<article class=\"sub\">\r\n");
      out.write("<p class=\"txt1\">「동물보호법」 제17조, 같은 법 시행령 제7조 및 같은 법 \r\n");
      out.write("시행규칙 제20조에 따라 구조된 동물의 보호상황을 \r\n");
      out.write("아래와 같이 공고합니다. </p>\r\n");
      out.write("<div class=\"ani_photo\">\r\n");
      out.write("<img src=\"");
      out.print(p.getPopfile() );
      out.write("\" class=\"photoimg\" alt=\"\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"roundbox\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<colgroup>\r\n");
      out.write("\t <col width=\"40%\">\r\n");
      out.write("\t <col width=\"60%\">\r\n");
      out.write("\t</colgroup>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>공고번호</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getNoticeNo() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>품 종</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getKindCd() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>색 상</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getColorCd() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>성 별</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getSexCd() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>나이/체중</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getAge() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(p.getWeight() );
      out.write(" </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>접수일시</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getHappenDt() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>발생장소</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getHappenPlace() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>특 징</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getSpecialMark() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"last\">공고기한</th>\r\n");
      out.write("\t\t\t<td class=\"last lft\">");
      out.print(d_1 );
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(d_2 );
      out.write("</td>\r\n");
      out.write("\t\t</tr>                              \r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("<p class=\"txt1\">유기동물문의는 보호소에 연락하시기 바랍니다. </p>\r\n");
      out.write("<div class=\"roundbox\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<colgroup>\r\n");
      out.write("\t <col width=\"40%\">\r\n");
      out.write("\t <col width=\"60%\">\r\n");
      out.write("\t</colgroup>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>보호소이름</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getCareNm() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>보호장소</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getCareAddr() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getCareTel() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>관할기관</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getOrgNm() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>담당자</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getChargeNm() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>연락처</th>\r\n");
      out.write("\t\t\t<td class=\"lft\">");
      out.print(p.getOfficetel() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"last\">특이사항</th>\r\n");
      out.write("\t\t\t<td class=\"last lft\"> </td>\r\n");
      out.write("\t\t</tr>                              \r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("<p class=\"txt_ge\">상기 동물을 분실하신 소유주께서는 보호소로 문의\r\n");
      out.write("하시어 동물을 찾아가시기 바라며, 동물보호 법 \r\n");
      out.write("제17조의 규정에 따른 공고가 있는 날부터 10일이 \r\n");
      out.write("경과하여도 소유자 등을 알 수 없는 경우에는 유실물법 \r\n");
      out.write("제12조 및 민법 제253조의 규정에 불구하고 해당 \r\n");
      out.write("시,군,구자치구가 그 동물의 소유권을 취득하게 됩니다.</p>\r\n");
      out.write("<p class=\"txt_end\">");
      out.print(date1 );
      out.write("</p>\r\n");
      out.write("</article>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
